### ISSUE TITLE
Issue: using build number instead of semver

### ISSUE THREAD

**Issue by praseodym** [rusenask/keel#67]
We're using CI build numbers as version numbers for our internal applications, and tag our images accordingly (e.g. `application:42` for build number 42). However, keel will try to parse this raw version number as a semver number, i.e. `42.0.0`. 
```
time="2017-07-30T15:32:37Z" level=info msg="provider.kubernetes: checking image" image="application:42.0.0" name=password namespace=default parsed_image_name="index.docker.io/application:42.0.0" policy=force target_image_name=application target_tag=42.0.0
```

Would it be possible to have proper support for build numbers as a version tag?

**Comment by rusenask** [comment]
You can use `force` policy with webhooks so it will always update once new image is available.

**Comment by praseodym** [comment]
I've tried this, but it doesn't work:
```
time="2017-07-30T18:27:08Z" level=info msg="provider.kubernetes: delta changed applied: application:42.0.0"
```
i.e. keel deploys `42.0.0` instead of the correct `42` tag.

**Comment by rusenask** [comment]
That's a bug then :/ will fix it.

**Comment by rusenask** [comment]
So the problem was this https://github.com/Masterminds/semver/blob/master/version.go#L54-L93. It treats emptiness as zeroes and I actually couldn't find a good reason to remove this. It's not semver but this behaviour actually lets you use `major` policy to incrementally update your application. Fixes are in the master branch and will be released with some other new features. Meanwhile I started `alpha` tag build, that image with fix should be available shortly.

**Comment by praseodym** [comment]
Thank you, I'll give the `alpha` tag a try.

**Comment by rusenask** [comment]
This is definitely merged and is available from 0.4.3.

**Comment by praseodym** [comment]
Thank you! We've upgraded to `0.4.4` and it works great.

**Comment by rusenask** [comment]
hey, there was similar issue with polling trigger, fix was just (12 minutes ago) merged in `0.4.5` :)

**Comment by praseodym** [comment]
I just noticed and upgraded 😄

**Comment by rusenask** [comment]
good, very agile :D
