### ISSUE TITLE
Exclusive version updates

### ISSUE THREAD

**Issue by stevenbarragan** [rusenask/keel#98]
Is it possible to have a policy to update on:

only patch changes:
```
  from 1.0.1 => 1.0.2 = update
  from 1.0.1 => 1.2.0 = do not update
  from 1.2.0 => 1.2.1 = update
```

only minor changes:
```
  form 1.0.1 => 1.0.2 = do not update
  form 1.0.1 => 1.2.0 = update
  form 1.2.0 => 1.2.1 = do not update
  form 1.2.1 => 2.0.0 = do no update
```

only mayor changes:
```
  from 1.0.0 => 1.0.1 = do not update
  from 1.0.0 => 1.1.0 = do not update
  from 1.1.0 => 2.0.0 = update
  from 2.0.0 => 2.0.1 = do not update
```

But why? I have 3 environments, development > staging > production, and I'm thinking I can increment the patch version for development releases, then the minor version for staging releases, and the mayor for production.

But I need, for example, production exclusively only watch mayor changes, staging only watch minor changes, and development for patch updates.

You you think I can set this up? good or bad idea? can somebody point me into the right direction to implement this?

Thanks in advance.

**Comment by rusenask** [comment]
Hi, currently this approach would only work for patch releases. I guess it would be good to understand your versioning - major version informs about backwards incompatible changes, introduced to the public API, right?

Maybe we could use build metadata for this (http://semver.org/):
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Or it could be additional annotation/label. But it does sound a bit redundant since all patch versions should be okay in minor version policy.

Have you considered having separate docker images from dev/staging/prod environments?

**Comment by stevenbarragan** [comment]
Yeah, it feels that I'm trying to bend semver rules. I need to rethink my workflow.

Thank you.
